#!/usr/bin/env python3
"""
Build the column-catalog stand-in: the data team's tag catalog for the music store database, the way
BigQuery policy tags or a Postgres table of tags would list them, served by a second MCP Toolbox
server as the named query `aiso_column_tags` that AI Stackops' Toolbox reader expects.

    python3 drafts/classification/generate_column_catalog.py [--music ../data/music-store/musicstore.sqlite]
                                                              [--out data/column-catalog] [--variant initial|retagged]

Standard library only. Writes <out>/catalog.sqlite (replaced) and <out>/tools.yaml.

The catalog lists EVERY column of the music store, tagged or not: a column the catalog does not list
is unknown to AISO, and a statement that reads its table then fails closed on it (column-filter.ts,
"tables"). One row per column and tag; a table-level tag has an empty column and domain 'table'.

--variant retagged adds what the data team does later in the demo: `contact = address` on
Customer.Address (mapped to internal), below what the classifier recorded for it. When catalog.sqlite
already exists it is changed IN PLACE (never replaced: the running Toolbox server holds it open), so
the next sync sees the change. On a live install point --out at the installed bundle folder
(<workspace>/bundles/aiso-demo-pack/column-catalog), or run the SQL in NOTES.md.
"""
from __future__ import annotations

import argparse
import os
import sqlite3

DATABASE = "musicstore"

# (table, column or None for the table, tag, value, masked) — the data team's tags.
TAGS: list[tuple[str, str | None, str, str, int]] = [
    ("Customer", "Email", "pii", "email", 1),
    ("Customer", "Phone", "pii", "phone", 0),
    ("Invoice", "Total", "finance", "revenue", 0),
    ("Invoice", None, "retention", "7y", 0),          # a tag the taxonomy does not map: column-tag-unmapped
    ("Employee", None, "hr", "personnel", 0),         # every Employee column inherits it: confidential HR
    ("Employee", "BirthDate", "hr", "date_of_birth", 0),  # restricted HR, no masking policy: column-unmasked
]
RETAGGED: list[tuple[str, str | None, str, str, int]] = [
    ("Customer", "Address", "contact", "address", 0),  # mapped to internal: below the classifier's opinion
]

TOOLS_YAML = """\
# The data team's column catalog for the music store (a stand-in for BigQuery policy tags), served by
# its own MCP Toolbox server so the tag query is not among the tools any agent is given. AI Stackops
# reads it through `columns.via` on the demo-data server. Generated by
# drafts/classification/generate_column_catalog.py.
sources:
  column-catalog:
    kind: sqlite
    database: catalog.sqlite

tools:
  aiso_column_tags:
    kind: sqlite-sql
    source: column-catalog
    description: Column tags on the music store database, one row per column and tag (untagged columns listed with no tag). Read by AI Stackops to classify columns; not for answering questions.
    statement: |
      SELECT "database", "schema", "table", "column", data_type, domain, tag, value, masked
      FROM column_tags
      ORDER BY "table", "column", tag
"""


def build(music: str, out: str, variant: str) -> tuple[int, int]:
    src = sqlite3.connect(f"file:{music}?mode=ro", uri=True)
    cols = src.execute(
        "SELECT m.name, p.name, p.type FROM sqlite_master m JOIN pragma_table_info(m.name) p "
        "WHERE m.type = 'table' AND m.name NOT LIKE 'sqlite_%' ORDER BY m.name, p.cid"
    ).fetchall()
    src.close()
    types = {(t, c): ty for t, c, ty in cols}

    tags = TAGS + (RETAGGED if variant == "retagged" else [])
    tagged_cols = {(t, c) for t, c, *_ in tags if c}
    for t, c, *_ in tags:
        if c and (t, c) not in types:
            raise SystemExit(f"tag on {t}.{c}, which the music store does not have")

    os.makedirs(out, exist_ok=True)
    path = os.path.join(out, "catalog.sqlite")
    if os.path.exists(path):
        os.remove(path)
    db = sqlite3.connect(path)
    db.execute(
        'CREATE TABLE column_tags ("database" TEXT NOT NULL, "schema" TEXT NOT NULL DEFAULT \'\', "table" TEXT NOT NULL, '
        '"column" TEXT, data_type TEXT, domain TEXT NOT NULL, tag TEXT, value TEXT, masked INTEGER NOT NULL DEFAULT 0)'
    )
    rows = []
    for (t, c), ty in types.items():
        if (t, c) not in tagged_cols:
            rows.append((DATABASE, "", t, c, ty, "column", None, None, 0))
    for t, c, tag, value, masked in tags:
        rows.append((DATABASE, "", t, c, types.get((t, c)) if c else None, "column" if c else "table", tag, value, masked))
    db.executemany("INSERT INTO column_tags VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)", rows)
    db.commit()
    db.close()
    with open(os.path.join(out, "tools.yaml"), "w") as f:
        f.write(TOOLS_YAML)
    return len(types), len(tags)


def retag_in_place(out: str) -> int:
    path = os.path.join(out, "catalog.sqlite")
    db = sqlite3.connect(path)
    n = 0
    for t, c, tag, value, masked in RETAGGED:
        have = db.execute('SELECT 1 FROM column_tags WHERE "table" = ? AND "column" = ? AND tag = ?', (t, c, tag)).fetchone()
        if have:
            continue
        ty = db.execute('SELECT data_type FROM column_tags WHERE "table" = ? AND "column" = ?', (t, c)).fetchone()
        db.execute('DELETE FROM column_tags WHERE "table" = ? AND "column" = ? AND tag IS NULL', (t, c))
        db.execute("INSERT INTO column_tags VALUES (?, '', ?, ?, ?, 'column', ?, ?, ?)", (DATABASE, t, c, ty[0] if ty else None, tag, value, masked))
        n += 1
    db.commit()
    db.close()
    return n


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    pack = os.path.normpath(os.path.join(here, "..", ".."))
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--music", default=os.path.join(pack, "data", "music-store", "musicstore.sqlite"))
    ap.add_argument("--out", default=os.path.join(pack, "data", "column-catalog"))
    ap.add_argument("--variant", choices=["initial", "retagged"], default="initial")
    a = ap.parse_args()
    if a.variant == "retagged" and os.path.exists(os.path.join(a.out, "catalog.sqlite")):
        print(f"{retag_in_place(a.out)} tag(s) added in place -> {a.out}/catalog.sqlite")
        return
    n, t = build(a.music, a.out, a.variant)
    print(f"{n} columns listed, {t} tags ({a.variant}) -> {a.out}")


if __name__ == "__main__":
    main()
